### PR TITLE
add TCP Route ADR

### PR DESCRIPTION
**Pull request by bengerman13**
## Changes proposed in this pull request:
- add TCP Route ADR

## security considerations
The ADR doesn't have any, but the implementation will

### CODE REVIEW

**Comment by mheadd** [comment]
Even if this is done with dedicated infra and insolation segments, the lack of TLS enforcement is still an issue right? That  tradeoff doesn't go away, we just isolate it in the new dedicated iso segment, correct?

**Comment by bengerman13** [comment]
the lack of TLS enforcement is still an issue, but it's also kind of the point of adding tcp termination:
the way PIV/CAC work is through the TLS handshake. Enforcing TLS termination requires us terminating TLS at the front door (ALB) then creating new TLS connections each step along the way.

**Comment by bengerman13** [comment]
We just heard back from one of the routing releases maintainers - it sounds like we can probably do this _without_ isolation segments.

**Review by mheadd — APPROVED** [review]
Thanks, @bengerman13!

**Pull request merged**
